version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      - GITLAB_ROOT_PASSWORD=verdaccio
      - GITLAB_HOST=http://localhost:50080/
      - GITLAB_OMNIBUS_CONFIG=gitlab_rails['registry_enabled'] = true; registry['registry_http_addr'] = 'http://localhost:50081/'; registry_external_url 'https://localhost:50081'
    ports:
      - '50080:80'
      - '50081:81'
      - '50022:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-log:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

  verdaccio:
    image: verdaccio/verdaccio
    restart: always
    ports:
      - '4873:4873'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - verdaccio:/verdaccio
    links:
      - gitlab

volumes:
  gitlab-config:
  gitlab-log:
  gitlab-data:
  verdaccio:
